#!/usr/bin/env bash
#set -x
has_colors() {
  if [[ -n ${HAS_COLORS+x} ]]; then
    :
  else
    case $TERM in
      *-256color) typeset -g HAS_COLORS=1 ;;
      vt100|dumb) typeset -g HAS_COLORS=0 ;;
      *)
        local colors
        case $OSTYPE in
          freebsd*|dragonfly*) colors=$(tput Co) ;;
          *) colors=$(tput colors) ;;
        esac
        declare -g HAS_COLORS=1
        ;;
    esac
  fi
  (( HAS_COLORS ))
}
has_colors "$@"

colornames() {
local BLACK=$'\e[0;30m'
local RED=$'\e[0;31m'
local GREEN=$'\e[0;32m'
local YELLOW=$'\e[0;33m'
local BlUE=$'\e[0;34m'
local PURPLE=$'\e[0;35m'
local CYAN=$'\e[0;36m'
local WHITE=$'\e[0;37m'

local BBLACK=$'\e[1;30m'
local BRED=$'\e[1;31m'
local BGREEN=$'\e[1;32m'
local BYELLOW=$'\e[1;33m'
local BBLUE=$'\e[1;34m'
local BPURPLE=$'\e[1;35m'
local BCYAN=$'\e[1;36m'
local BWHITE=$'\e[1;37m'

local HIBLACK=$'\e[0;90m'
local HIRED=$'\e[0;91m'
local HIGREEN=$'\e[0;92m'
local HIYELLOW=$'\e[0;93m'
local HIBLUE=$'\e[0;94m'
local HIPURPLE=$'\e[0;95m'
local HICYAN=$'\e[0;96m'
local HIWHITE=$'\e[0;97m'
local NC=$'\e[0'

printf '\n%s \t\t%s \t\t%s \t\t%s \t\t%s \t\t%s \t\t%s \t\t%s' "${RED}"' Red' "${GREEN}"'Green' "${YELLOW}"'Yellow' "${BlUE}"'Blue' "${PURPLE}"'Purple' "${CYAN}"'Cyan' "${WHITE}"'White' "${BLACK}"'Black'
printf '\n%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "${RED}"' \e[0;31m' "${GREEN}"'\e[0;32m' "${YELLOW}"'\e[0;33m' "${BlUE}"'\e[0;34m' "${PURPLE}"'\e[0;35m' "${CYAN}"'\e[0;36m' "${WHITE}"'\e[0;37m' "${BLACK}"'\e[0;30m'

printf '\n%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s' "${BRED}"' bold Red' "${BGREEN}"'bold Green' "${BYELLOW}"'bold Yellow' "${BBLUE}"'bold Blue' "${BPURPLE}"'bold Purple' "${BCYAN}"'bold Cyan' "${BWHITE}"'bold White' "${BBLACK}"' bold Black'
printf '\n%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "${BRED}"' \e[1;31m' "${BGREEN}"'\e[1;32m' "${BYELLOW}"'\e[1;33m' "${BBLUE}"'\e[1;34m' "${BPURPLE}"'\e[1;35m' "${BCYAN}"'\e[1;36m' "${BWHITE}"'\e[1;37m' "${BBLACK}"' \e[1;30m'

printf '\n%s\t%s\t%s\t%s\n%s\t\t%s\t\t%s\t\t%s\n' "${HIRED}"' high intensity Red' "${HIGREEN}"'high intensity Green' "${HIYELLOW}"'high intensity Yellow' "${HIBLACK}"'high intensity Black' "${HIRED}"' \e[0;91m' "${HIGREEN}"'\e[0;92m' "${HIYELLOW}"'\e[0;93m' "${HIBLACK}"'\e[0;90m'

printf '\n%s\t%s\t%s\t%s\n%s\t\t%s\t\t%s\t\t%s%s\n' "${HIBLUE}"' high intensity Blue' "${HIPURPLE}"'high intensity Purple' "${HICYAN}"'high intensity Cyan' "${HIWHITE}"'high intensity White' "${HIBLUE}"' \e[0;94m' "${HIPURPLE}"'\e[0;95m' "${HICYAN}"'\e[0;96m' "${HIWHITE}"'\e[0;97m' "${NC}"
}
colornames "$@"
