#!/bin/env zsh
# shellcheck disable=SC2086
################################################################################
#                                                                              #
# Copyright 2023-2025 Thomas Bernard (https://github.com/TomfromBerlin)        #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of this software and associated documentation files (the “Software”), to     #
# deal in the Software without restriction, including without limitation the   #
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or  #
# sell copies of the Software, and to permit persons to whom the Software is   #
# furnished to do so, subject to the following conditions:                     #
#                                                                              #
# The above copyright notice and this permission notice shall be included in   #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE  #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER       #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING      #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS #
# IN THE SOFTWARE.                                                             #
#                                                                              #
################################################################################
#                                                                              #
# Description:                                                                 #
# Convert temperature values from Celsius to Fahrenheit and Kelvin and back.   #
# You'll also get an output in joules and electron volt - just for fun.        #
#                                                                              #
# Usage: run 'bash /path/to/file/temp_conv' or                                 #
#            'zsh /path/to/file/temp_conv'                                     #
#        in your terminal. In Z shell you can put the file in a directory in   #
#        your $fpath and use it as a function (yes, it works even with that    #
#        shebang). In this case you may take care of the Z shell loading time. #
#                                                                              #
################################################################################
#set -x

has_colors() {
  if [[ -n ${HAS_COLORS+x} ]]; then
    :
  else
    case $TERM in
      *-256color) declare -g HAS_COLORS=1 ;;
      vt100|dumb) declare -g HAS_COLORS=0 ;;
      *)
        local colors
        case $OSTYPE in
          freebsd*|dragonfly*) colors=$(tput Co) ;;
          *) colors=$(tput colors) ;;
        esac
        declare -g HAS_COLORS=1
        ;;
    esac
  fi
  (( HAS_COLORS ))
}
has_colors "$@"

export LC_NUMERIC=C
CELSIUS2KELVIN='273.15'
KELVIN2eV='11604.5'
KELVIN2JOULES="$(echo | awk '{print (1.38064878066852 * (10^-23))}')" # ¯\_(ツ)_/¯
FAHRENHEIT_ROTCAF='5/9'
FAHRENHEIT_FACTOR='9/5'
summ='32'

kelvin_info() {
cat <<_info1_
 -------------------------------------------------------------------------------
 According to the new definition of the temperature unit (since May 2019), the
 Kelvin is no longer defined via the fixed point temperature of water.
 Instead, temperatures will then be defined with direct reference to energy.
 In doing so, we use the value of the Boltzmann constant k, so 1 Kelvin is equal
 to 1.38064878066852 x 10e-23 joules.
 The Celsius scale will have the same relation to the Kelvin after May 2019 as
 before.
 -------------------------------------------------------------------------------

_info1_
local GREEN=$'\e[0;32m'
local PURPLE=$'\e[0;35m'
local NC=$'\e[0m' # reset color

printf '\n%s\n' ' Enter '${PURPLE}'m'${NC}' to retry, '${PURPLE}'i'${NC}' for more information, any other key to quit: '${GREEN} && read -r _input && echo -e ${NC}

     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        m) temp_conv ;;
        i) absolute_zero ;;
        *) return ;;
     esac
}

absolute_zero() {
cat <<_info2_

-------------------------------------------------------------------------------

                               Absolute zero

  The third and last law of thermodynamics - also known as the Nernst theorem -
  states that a system cannot be cooled to absolute zero.

  At absolute zero, which corresponds to a temperature of

         0 Kelvin or -273.15 °Celsius or -459.67 °Fahrenheit,

  no more particles can oscillate.

  However, this only happens in a perfect ice crystal, which extends to
  infinity in a constant and perfect lattice structure.
  Theoretically imaginable, practically not possible.

  And why is this so? Let's take a look at a lattice structure.

  Perfect crystals never occur in practice; imperfections, and even entire
  amorphous material inclusions, can and do get "frozen in" at low temperatures,
  so transitions to more stable states do not occur.

  As soon as there is an imperfection, no matter how small, irregularities show
  up. This is because the environment and thus the intermolecular forces change
  for some particles. Particle 1, for example, has a different environment than
  particle 2.

  Now we can differentiate between places with low entropy and those with
  higher entropy, i.e. where the disorder is greater and there are consequently
  more oscillation possibilities - in our case, this would be particle 2.

  Consequently, the entropy can never be really zero.

     lim ΔS = 0
     T ⟶ 0

  That is, for a temperature close to absolute zero the entropy limit runs to
  zero.

  Even a system at absolute zero, if it could somehow be achieved, would still
  possess quantum mechanical zero-point energy, the energy of its ground state
  at absolute zero; the kinetic energy of the ground state cannot be removed.

-------------------------------------------------------------------------------

_info2_
local GREEN=$'\e[0;32m'
local PURPLE=$'\e[0;35m'
local NC=$'\e[0m' # reset color

printf '%s\n\n' ' Enter '${PURPLE}'m'${NC}' to retry, '${PURPLE}'i'${NC}' for more information, any other key to quit: '${GREEN} && read -r _input && echo -en ${NC}

     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        m) temp_conv ;;
        i) kelvin_info ;;
        *) return ;;
     esac
}

Celsius2Fahrenheit() {
local UNIT='°C'
local LOWEST='-273.15'
local RED=$'\e[0;31m'
local REDBOLD=$'\e[1;31m'
local GREEN=$'\e[0;32m'
local ORANGE=$'\e[0;33m'
local PURPLE=$'\e[0;35m'
local CYAN=$'\e[0;36m'
local NC=$'\e[0m' # reset color

  printf '\n'
  printf '%s' ' Please enter a value for '${PURPLE}'Celsius'${NC}': ' ${CYAN} && read -r VALUE_CELSIUS && echo -en ${NC}
  if [[ $VALUE_CELSIUS =~ ^[+-]?[0-9]+\,?[0-9]?*$ ]] ; then VALUE_CELSIUS=${VALUE_CELSIUS/,/.} ;fi
  if [ "$(echo -e "$VALUE_CELSIUS $LOWEST" | awk '{print ( $1 < $2 )}')" = 1 ] ; then printf '\n%s' ' Values lower than '${REDBOLD}''${LOWEST}''${UNIT}''${NC}' are not permissible, since '${LOWEST}''${UNIT}' equals 0 Kelvin, and according to the laws of thermodynamics 0 Kelvin is the lowest possible temperature.'
  printf '\n%s' ' Enter '${PURPLE}'r'${NC}' to retry, '${PURPLE}'m'${NC}' for menu, any other key to quit: '${GREEN} && read -r _input && echo -en ${NC}
     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        r) Celsius2Fahrenheit ;;
        m) temp_conv ;;
        i) absolute_zero ;;
        *) return ;;
     esac
  elif [[ $VALUE_CELSIUS =~ ^[+-]?[0-9]+\.?[0-9]?*$ ]] ; then
  FAHRENHEIT=$(echo -en $VALUE_CELSIUS | awk '{print ( '$VALUE_CELSIUS' * '$FAHRENHEIT_FACTOR' ) + '$summ'}')
  KELVIN="$(echo -en $VALUE_CELSIUS | awk '{print ( '$VALUE_CELSIUS' + '$CELSIUS2KELVIN' )}')"
  eV="$(echo -en $KELVIN | awk '{print ( '$KELVIN' * '$KELVIN2eV' )}')"
  JOULES="$(echo -en $KELVIN | awk '{print ( '$KELVIN' * '$KELVIN2JOULES' )}')"
  printf '\n%s\n' ' The conversion formula is '${ORANGE}'('${VALUE_CELSIUS}'°C × '${FAHRENHEIT_FACTOR}') + '${summ}''${NC}' and gives '$GREEN''${FAHRENHEIT}'°F'${NC}', which is '${GREEN}''${KELVIN}' Kelvin'${NC}', '${GREEN}''${JOULES}' Joules'${NC}' and '${GREEN}''${eV}' eV'${NC}'.' && VALUE_FAHRENHEIT="" && return
  else printf '\n%s%s' ${RED}' No valid input!'${NC}' Enter '${PURPLE}'r'${NC}' to retry, '${PURPLE}'m'${NC}' for menu, any other key to quit: '${GREEN} && read -r _input && echo -en ${NC}
     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        r) Celsius2Fahrenheit ;;
        m) temp_conv ;;
        *) return ;;
     esac
  fi
}

Fahrenheit2Celsius() {
local UNIT='°F'
local LOWEST=$'-459.67'
local RED=$'\e[0;31m'
local REDBOLD=$'\e[1;31m'
local GREEN=$'\e[0;32m'
local ORANGE=$'\e[0;33m'
local PURPLE=$'\e[0;35m'
local CYAN=$'\e[0;36m'
local NC=$'\e[0m' # reset color

  printf '\n'
  printf '%s' ' Please enter a value for '${PURPLE}'Fahrenheit'${NC}': ' ${CYAN} && read -r VALUE_FAHRENHEIT && echo -en ${NC}
  if [[ $VALUE_FAHRENHEIT =~ ^[+-]?[0-9]+\,?[0-9]*$ ]] ; then VALUE_FAHRENHEIT=${VALUE_FAHRENHEIT/,/.} ;fi
  if [ "$(echo -e "$VALUE_FAHRENHEIT $LOWEST" | awk '{print ( $1 < $2 )}')" = 1 ] ; then printf '\n%s' ' Values lower than '${REDBOLD}''${LOWEST}''${UNIT}''${NC}' are not permissible, since '${LOWEST}''${UNIT}' equals 0 Kelvin, and according to the laws of thermodynamics 0 Kelvin is the lowest possible temperature.'
  printf '\n%s' ' Enter '${PURPLE}'r'${NC}' to retry, '${PURPLE}'m'${NC}' for menu, any other key to quit: '${GREEN} && read -r _input && echo -en ${NC}
     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        r) Fahrenheit2Celsius ;;
        m) temp_conv ;;
        i) absolute_zero ;;
        *) return ;;
     esac
  elif [[ $VALUE_FAHRENHEIT =~ ^[+-]?[0-9]+\.?[0-9]?*$ ]] ; then
  CELSIUS="$(echo -en $VALUE_FAHRENHEIT | awk '{ print ( '$VALUE_FAHRENHEIT' - '$summ' ) * '$FAHRENHEIT_ROTCAF' }')"
  KELVIN="$(echo -en $CELSIUS | awk '{print ( '$CELSIUS' + '$CELSIUS2KELVIN' )}')"
  eV="$(echo -en $KELVIN | awk '{print ( '$KELVIN' * '$KELVIN2eV' )}')"
  JOULES="$(echo -en $KELVIN | awk '{print ( '$KELVIN' * '$KELVIN2JOULES' )}')"
  printf '\n%s\n' ' The conversion formula is '${ORANGE}'('${VALUE_FAHRENHEIT}'°F − '${summ}') × '${FAHRENHEIT_ROTCAF}''${NC}' and gives '${GREEN}''${CELSIUS}'°C'${NC}', which is '${GREEN}''${KELVIN}' Kelvin'${NC}', '${GREEN}''${JOULES}' Joules'${NC}' and '${GREEN}''${eV}' eV'${NC}'.' && VALUE_FAHRENHEIT="" && return
  else printf '\n%s\n%s\n%s' ${RED}' No valid input!'${NC} ' Press'${PURPLE}' r'${NC}' to retry,'${PURPLE}' i'${NC}' for more information,' ' or any other key to quit: '${GREEN} && read -r _input && echo -en ${NC}
     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        r) Fahrenheit2Celsius ;;
        m) temp_conv ;;
        *) return ;;
     esac
  fi
}

Kelvin2Celsius() {
local UNIT='Kelvin'
local LOWEST=$'0'
local RED=$'\e[0;31m'
local REDBOLD=$'\e[1;31m'
local GREEN=$'\e[0;32m'
local ORANGE=$'\e[0;33m'
local PURPLE=$'\e[0;35m'
local CYAN=$'\e[0;36m'
local NC=$'\e[0m' # reset color

  echo ""
  printf '%s' ' Please enter a value for '${PURPLE}'Kelvin'${NC}': ' ${CYAN} && read -r value_kelvin && echo -en ${NC}
  if [[ $value_kelvin =~ ^[+-]?[0-9]+\,?[0-9]*$ ]] ; then value_kelvin=${value_kelvin/,/.} ;fi
  if [[ $value_kelvin =~ ^[-][0-9]+\.?[0-9]*$ ]] ; then
  printf '\n\n%s' ' Values lower than '${REDBOLD}''${LOWEST}''${UNIT}''${NC}' are not permissible, since according to the laws of thermodynamics 0 Kelvin is the lowest possible temperature.'
  printf '\n\n%s%s%s' '  Press '${PURPLE}'m'${NC}' to retry, '${PURPLE}'i'${NC}' for more information, or any other key to quit: '${GREEN} && read -r _input && echo -en ${NC}
     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        m) temp_conv ;;
        i) absolute_zero ;;
        *) return ;;
     esac
  elif [[ $value_kelvin =~ ^[+]?[0-9]+\.?[0-9]?*$ ]]; then
  CELSIUS="$(echo -en $value_kelvin | awk '{ print ( '$value_kelvin' - '$CELSIUS2KELVIN' ) }')"
  FAHRENHEIT="$(echo -en $CELSIUS | awk '{print (( '$CELSIUS' * '$FAHRENHEIT_FACTOR' ) + '$summ' ) }')"
  eV="$(echo -en $value_kelvin | awk '{print ( '$value_kelvin' * '$KELVIN2eV' )}')"
  JOULES="$(echo -en $value_kelvin | awk '{print ( '$value_kelvin' * '$KELVIN2JOULES' )}')"
  printf '\n%s\n' ' The conversion formula is '${ORANGE}''${value_kelvin}' K − '${CELSIUS2KELVIN}''${NC}' and gives '${GREEN}''$CELSIUS'°C'${NC}', which is '${GREEN}''$FAHRENHEIT'°F'${NC}', '${GREEN}''${JOULES}' Joules'${NC}' and '${GREEN}''${eV}' eV'${NC}'.' && value_kelvin="" && return
  else printf '\n%s\n%s\n%s' ${RED}' No valid input!'${NC} ' Press'${PURPLE}' r'${NC}' to retry,'${PURPLE}' i'${NC}' for more information,' ' or any other key to quit: '${GREEN} && read -r _input && echo -en ${NC}
     _input=$(echo "$_input" | tr '[:upper:]' '[:lower:]')
     case $_input in
        r) Kelvin2Celsius ;;
        m) temp_conv ;;
        *) return ;;
     esac
  fi
}

temp_conv() {
local GREEN=$'\e[0;32m'
local PURPLE=$'\e[0;35m'
local CYAN=$'\e[0;36m'
local NC=$'\e[0m' # reset color

  printf '\n%s\n' 'Enter'
  printf '%s\n'${PURPLE}'    C'${NC}' for '${CYAN}'Celsius (°C)    '${NC}'-> '${GREEN}'Fahrenheit (°F) '${NC}'->'${GREEN}' Kelvin (K)      '${NC}'->'${GREEN}' Joule (J) '${NC}'->'${GREEN}' Electron Volt (eV)'${NC}' conversion'
  printf '%s\n'${PURPLE}'    F'${NC}' for '${CYAN}'Fahrenheit (°F) '${NC}'->'${GREEN}' Celsius (°C)    '${NC}'->'${GREEN}' Kelvin (K)      '${NC}'->'${GREEN}' Joule (J) '${NC}'->'${GREEN}' Electron Volt (eV)'${NC}' conversion'
  printf '%s\n'${PURPLE}'    K'${NC}' for '${CYAN}'Kelvin (K)      '${NC}'->'${GREEN}' Celsius (°C)    '${NC}'->'${GREEN}' Fahrenheit (°F) '${NC}'->'${GREEN}' Joule (J) '${NC}'->'${GREEN}' Electron Volt (eV)'${NC}' conversion'
  printf '\n%s\n'${CYAN}'    any other key to abort'${NC}
  printf '\n\n%s'  '(case insensitive): '${GREEN} && read -r _value && printf '%s' "${NC}"
  _value=$(echo "$_value" | tr '[:upper:]' '[:lower:]')
     case "$_value" in
        c) Celsius2Fahrenheit ;;
        f) Fahrenheit2Celsius ;;
        k) Kelvin2Celsius ;;
        *) printf '\n\t%s\n' "${RED}Abort!${NC}" && return ;;
     esac
}

temp_conv "$@"
